// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4c8FY6i8By_mSMpBFpMF8T6USUR-JHI',
    appId: '1:79093040677:web:3640ed040f21312a6221cc',
    messagingSenderId: '79093040677',
    projectId: 'momentum-fdb1e',
    authDomain: 'momentum-fdb1e.firebaseapp.com',
    storageBucket: 'momentum-fdb1e.firebasestorage.app',
    measurementId: 'G-8HQGGGPDBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9qr1cvb4dG2lH5oj2uGnnvFr-Mfvt2c',
    appId: '1:79093040677:android:9aa66bbc8fc37a3c6221cc',
    messagingSenderId: '79093040677',
    projectId: 'momentum-fdb1e',
    storageBucket: 'momentum-fdb1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3_HLBQa1YXRZDvD8RF3uSlgW8yDRGiNE',
    appId: '1:79093040677:ios:12ccaac860cdbf8b6221cc',
    messagingSenderId: '79093040677',
    projectId: 'momentum-fdb1e',
    storageBucket: 'momentum-fdb1e.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3_HLBQa1YXRZDvD8RF3uSlgW8yDRGiNE',
    appId: '1:79093040677:ios:12ccaac860cdbf8b6221cc',
    messagingSenderId: '79093040677',
    projectId: 'momentum-fdb1e',
    storageBucket: 'momentum-fdb1e.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4c8FY6i8By_mSMpBFpMF8T6USUR-JHI',
    appId: '1:79093040677:web:9d4e7c8d80a4569d6221cc',
    messagingSenderId: '79093040677',
    projectId: 'momentum-fdb1e',
    authDomain: 'momentum-fdb1e.firebaseapp.com',
    storageBucket: 'momentum-fdb1e.firebasestorage.app',
    measurementId: 'G-FWC458VM24',
  );
}
